from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image,
    Table,
    TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
import os
from pathlib import Path


def generate_pdf(results, ai_summary, output_path):

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    title = styles["Title"]
    heading = styles["Heading2"]
    normal = styles["BodyText"]

    story = []

    # Title
    story.append(
        Paragraph(
            "CFD AI Assistant - Simulation Report",
            title
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Computational Fluid Dynamics Analysis of Water Flow Through a Pipe",
            normal
        )
    )

    story.append(Spacer(1, 20))

    # CFD Results
    story.append(
        Paragraph("1. CFD Simulation Results", heading)
    )

    data = [
        ["Parameter", "Value"],
        ["Average Velocity", f'{results["average_velocity"]:.4f} m/s'],
        ["Maximum Velocity", f'{results["maximum_velocity"]:.4f} m/s'],
        ["Minimum Velocity", f'{results["minimum_velocity"]:.4f} m/s'],
        ["Maximum Pressure", f'{results["maximum_pressure"]:.2f} Pa'],
        ["Minimum Pressure", f'{results["minimum_pressure"]:.2f} Pa'],
        ["Pressure Drop", f'{results["pressure_drop"]:.2f} Pa'],
        ["Flow Rate", f'{results["flow_rate"]:.6f} m³/s'],
        ["Reynolds Number", f'{results["reynolds_number"]:.2f}'],
        ["Flow Regime", results["flow_regime"]],
    ]

    table = Table(data, colWidths=[220, 220])

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
            ("GRID", (0, 0), (-1, -1), 1, colors.grey),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
            ("TOPPADDING", (0, 0), (-1, 0), 8),
        ])
    )

    story.append(table)

    story.append(Spacer(1, 25))

    # Graphs
    story.append(
        Paragraph("2. Velocity Distribution", heading)
    )

    project_folder = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    generated_folder = os.path.join(project_folder, "generated")

    velocity_graph = os.path.join(generated_folder, "velocity.png")
    pressure_graph = os.path.join(generated_folder, "pressure.png")

    print("VELOCITY PATH:", velocity_graph)
    print("VELOCITY EXISTS:", os.path.exists(velocity_graph))

    print("PRESSURE PATH:", pressure_graph)
    print("PRESSURE EXISTS:", os.path.exists(pressure_graph))

    if os.path.exists(velocity_graph):
        print("Velocity path:", velocity_graph)
        print("Velocity exists:", os.path.exists(velocity_graph))

        print("Pressure path:", pressure_graph)
        print("Pressure exists:", os.path.exists(pressure_graph))

        print("Velocity graph:", velocity_graph)
        print("Exists:", os.path.exists(velocity_graph))

        print("Pressure graph:", pressure_graph)
        print("Exists:", os.path.exists(pressure_graph))

        story.append(
            Image(
                velocity_graph,
                width=6 * inch,
                height=3.75 * inch
            )
        )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph("3. Pressure Distribution", heading)
    )

    pressure_graph = os.path.join(
        "generated",
        "pressure.png"
    )

    if os.path.exists(pressure_graph):

        story.append(
            Image(
                pressure_graph,
                width=6 * inch,
                height=3.75 * inch
            )
        )

    story.append(Spacer(1, 20))

    # AI analysis
    story.append(
        Paragraph(
            "4. AI Engineering Analysis",
            heading
        )
    )

    # Convert newlines into HTML breaks
    ai_text = ai_summary.replace("\n", "<br/>")

    story.append(
        Paragraph(
            ai_text,
            normal
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Generated by CFD AI Assistant",
            normal
        )
    )

    doc.build(story)

    return output_path